#!/usr/bin/env python3
import argparse
import os
import re
import sys
import gzip
from typing import Tuple

def die(msg: str) -> int:
    print(f"playbox_pack.py: error: {msg}", file=sys.stderr)
    return 1

def c_ident(name: str) -> str:
    # turn "foo-bar.txt" into "foo_bar_txt"
    s = re.sub(r'[^a-zA-Z0-9_]', '_', name)
    if not s or not (s[0].isalpha() or s[0] == '_'):
        s = "_" + s
    return s

def read_file(path: str) -> bytes:
    with open(path, "rb") as f:
        return f.read()

def maybe_gzip(data: bytes, enable: bool) -> Tuple[bytes, bool]:
    if not enable:
        return data, False
    out = gzip.compress(data, compresslevel=9)
    return out, True

def emit_header_prologue(namespace: str) -> str:
    guard = c_ident(namespace.upper() + "_PACKED_H")
    return (
        f"#ifndef {guard}\n"
        f"#define {guard}\n\n"
        f"// Generated by tools/py/playbox_pack.py\n"
        f"#include <stddef.h>\n"
        f"#include <stdint.h>\n\n"
    )

def emit_header_epilogue(namespace: str) -> str:
    guard = c_ident(namespace.upper() + "_PACKED_H")
    return f"\n#endif // {guard}\n"

def emit_bin(symbol: str, data: bytes, note: str) -> str:
    sym = c_ident(symbol)
    lines = []
    lines.append(f"// {note}")
    lines.append(f"static const unsigned char {sym}[] = {{")
    # hex rows
    for i in range(0, len(data), 12):
        chunk = data[i:i+12]
        row = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"    {row},")
    if len(data) == 0:
        lines.append("    0x00,")
    lines.append("};")
    lines.append(f"static const size_t {sym}_len = {len(data)}u;")
    return "\n".join(lines) + "\n"

def emit_text(symbol: str, data: bytes, note: str) -> str:
    # store as char array with explicit bytes (safe for any UTF-8)
    sym = c_ident(symbol)
    lines = []
    lines.append(f"// {note}")
    lines.append(f"static const char {sym}[] = {{")
    for i in range(0, len(data), 12):
        chunk = data[i:i+12]
        row = ", ".join(f"(char)0x{b:02X}" for b in chunk)
        lines.append(f"    {row},")
    lines.append("    (char)0x00, // NUL terminator")
    lines.append("};")
    lines.append(f"static const size_t {sym}_len = {len(data)}u;")
    return "\n".join(lines) + "\n"

def main() -> int:
    ap = argparse.ArgumentParser(prog="playbox_pack.py", description="Pack assets into a C header for Playbox demos.")
    ap.add_argument("--namespace", default="playbox_assets", help="Header guard namespace (default: playbox_assets)")
    sub = ap.add_subparsers(dest="cmd", required=True)

    p_text = sub.add_parser("pack-text", help="Pack a UTF-8 text file as const char[]")
    p_text.add_argument("input", help="Input file path")
    p_text.add_argument("--symbol", default=None, help="C symbol name (default: derived from filename)")
    p_text.add_argument("-o", "--output", required=True, help="Output header path")
    p_text.add_argument("--gz", action="store_true", help="Gzip-compress the bytes before embedding")

    p_bin = sub.add_parser("pack-bin", help="Pack a binary file as const unsigned char[]")
    p_bin.add_argument("input", help="Input file path")
    p_bin.add_argument("--symbol", default=None, help="C symbol name (default: derived from filename)")
    p_bin.add_argument("-o", "--output", required=True, help="Output header path")
    p_bin.add_argument("--gz", action="store_true", help="Gzip-compress the bytes before embedding")

    args = ap.parse_args()

    in_path = getattr(args, "input", None)
    if not in_path or not os.path.isfile(in_path):
        return die(f"input file not found: {in_path}")

    base = os.path.basename(in_path)
    symbol = args.symbol or c_ident(os.path.splitext(base)[0])

    raw = read_file(in_path)
    packed, gz = maybe_gzip(raw, getattr(args, "gz", False))

    pro = emit_header_prologue(args.namespace)
    epi = emit_header_epilogue(args.namespace)

    note = f"source: {base} ({len(raw)} bytes)" + (" [gzipped]" if gz else "")

    body = ""
    if args.cmd == "pack-text":
        body = emit_text(symbol, packed, note)
        if gz:
            body += f"// NOTE: {c_ident(symbol)} is gzipped bytes; you must gunzip at runtime to get original text.\n"
    elif args.cmd == "pack-bin":
        body = emit_bin(symbol, packed, note)
        if gz:
            body += f"// NOTE: {c_ident(symbol)} is gzipped bytes; you must gunzip at runtime to get original binary.\n"
    else:
        return die("unknown command")

    out = pro + body + epi
    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(out)

    print(f"wrote {args.output}  (symbol={c_ident(symbol)} len={len(packed)} gz={'yes' if gz else 'no'})")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
