use std::env;
use std::fs;
use std::io::{self, Read};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

fn usage() -> ! {
    eprintln!(
        r#"playbox - helper CLI for PlayboxLib

        USAGE:
        playbox doctor
        playbox info
        playbox pack-text <input> -o <output.h> [--symbol <name>]
        playbox pack-bin  <input> -o <output.h> [--symbol <name>]

        playbox demo   <name> [--bin-dir <dir>]
        playbox record <name> -o <file.pbr> [--bin-dir <dir>]
        playbox replay <name> -i <file.pbr> [--bin-dir <dir>]

        playbox cat

        NOTES:
        - demo/record/replay expects a demo executable named exactly <name>
        - default bin dir tries: ./build, ./build/bin, ./bin, ./out, .
        - record sets PLAYBOX_RECORD, replay sets PLAYBOX_REPLAY
        "#
    );
    std::process::exit(2);
}

fn default_bin_dirs() -> Vec<PathBuf> {
    vec![
        PathBuf::from("./build"),
        PathBuf::from("./build/bin"),
        PathBuf::from("./bin"),
        PathBuf::from("./out"),
        PathBuf::from("."),
    ]
}

fn find_demo(bin_dir: Option<&str>, name: &str) -> Option<PathBuf> {
    let mut dirs = Vec::new();
    if let Some(d) = bin_dir {
        dirs.push(PathBuf::from(d));
    } else {
        dirs.extend(default_bin_dirs());
    }

    for d in dirs {
        let p = d.join(name);
        if p.is_file() {
            return Some(p);
        }
    }
    None
}

fn run_demo(path: &Path, extra_env: &[(&str, &str)]) -> i32 {
    let mut cmd = Command::new(path);
    cmd.stdin(Stdio::inherit())
    .stdout(Stdio::inherit())
    .stderr(Stdio::inherit());

    for (k, v) in extra_env {
        cmd.env(k, v);
    }

    match cmd.status() {
        Ok(s) => s.code().unwrap_or(1),
        Err(e) => {
            eprintln!("playbox: failed to run {:?}: {}", path, e);
            1
        }
    }
}

fn cmd_cat() -> i32 {
    let mut s = String::new();
    let _ = io::stdin().read_to_string(&mut s);
    if s.trim().is_empty() {
        println!("playbox cat: pipe text in");
    } else {
        print!("{}", s);
    }
    0
}

fn cmd_doctor() -> i32 {
    let term = env::var("TERM").unwrap_or_else(|_| "(unset)".into());
    let colorterm = env::var("COLORTERM").unwrap_or_else(|_| "(unset)".into());
    let lang = env::var("LANG").unwrap_or_else(|_| "(unset)".into());

    println!("Playbox doctor:");
    println!("  TERM      = {}", term);
    println!("  COLORTERM = {}", colorterm);
    println!("  LANG      = {}", lang);

    let truecolor = colorterm.to_lowercase().contains("truecolor")
    || colorterm.to_lowercase().contains("24bit");
    println!("  truecolor = {}", if truecolor { "likely yes ✅" } else { "unknown ⚠️" });

    if term == "dumb" || term == "(unset)" {
        println!("  warning   = TERM looks sketchy; ANSI may not work well.");
    }

    println!("  tip: run inside a real terminal (kitty/alacritty/wezterm/foot/etc).");
    0
}

fn cmd_info() -> i32 {
    println!("Playbox baseline:");
    println!("  - pb_term: terminal game mode (raw/alt/mouse)");
    println!("  - pb_input: bytes -> events");
    println!("  - pb_fb: grid framebuffer (cells)");
    println!("  - pb_renderer: diff -> ANSI output");
    println!("  - pb_app: loop (events, dt, update, draw, present)");
    println!();
    println!("Deterministic goodies:");
    println!("  - PLAYBOX_RECORD=<file> records dt+events per frame");
    println!("  - PLAYBOX_REPLAY=<file> replays dt+events per frame");
    0
}

/* ------------------------- packer ------------------------- */

fn c_ident(name: &str) -> String {
    let mut s: String = name
    .chars()
    .map(|ch| if ch.is_ascii_alphanumeric() || ch == '_' { ch } else { '_' })
    .collect();
    if s.is_empty() || !(s.chars().next().unwrap().is_ascii_alphabetic() || s.starts_with('_')) {
        s.insert(0, '_');
    }
    s
}

fn file_stem_ident(path: &str) -> String {
    let p = Path::new(path);
    let stem = p.file_stem().and_then(|x| x.to_str()).unwrap_or("asset");
    c_ident(stem)
}

fn emit_guard(namespace: &str) -> (String, String) {
    let guard = c_ident(&(namespace.to_uppercase() + "_PACKED_H"));
    (
        format!(
            "#ifndef {g}\n#define {g}\n\n// Generated by tools/rust/playbox_cli\n#include <stddef.h>\n#include <stdint.h>\n\n",
            g = guard
        ),
     format!("\n#endif // {g}\n", g = guard),
    )
}

fn emit_bin(sym: &str, data: &[u8], note: &str) -> String {
    let sym = c_ident(sym);
    let mut out = String::new();
    out.push_str(&format!("// {}\n", note));
    out.push_str(&format!("static const unsigned char {}[] = {{\n", sym));
    if data.is_empty() {
        out.push_str("    0x00,\n");
    } else {
        for chunk in data.chunks(12) {
            out.push_str("    ");
            for (i, b) in chunk.iter().enumerate() {
                if i != 0 { out.push_str(", "); }
                out.push_str(&format!("0x{:02X}", b));
            }
            out.push_str(",\n");
        }
    }
    out.push_str("};\n");
    out.push_str(&format!("static const size_t {}_len = {}u;\n", sym, data.len()));
    out
}

fn emit_text(sym: &str, data: &[u8], note: &str) -> String {
    let sym = c_ident(sym);
    let mut out = String::new();
    out.push_str(&format!("// {}\n", note));
    out.push_str(&format!("static const char {}[] = {{\n", sym));
    for chunk in data.chunks(12) {
        out.push_str("    ");
        for (i, b) in chunk.iter().enumerate() {
            if i != 0 { out.push_str(", "); }
            out.push_str(&format!("(char)0x{:02X}", b));
        }
        out.push_str(",\n");
    }
    out.push_str("    (char)0x00, // NUL terminator\n");
    out.push_str("};\n");
    out.push_str(&format!("static const size_t {}_len = {}u;\n", sym, data.len()));
    out
}

fn write_header(namespace: &str, output: &str, body: &str) -> io::Result<()> {
    let (pro, epi) = emit_guard(namespace);
    let full = format!("{}{}{}", pro, body, epi);
    if let Some(parent) = Path::new(output).parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent)?;
        }
    }
    fs::write(output, full.as_bytes())
}

fn cmd_pack(kind: &str, input: &str, output: &str, symbol: Option<&str>) -> i32 {
    let data = match fs::read(input) {
        Ok(d) => d,
        Err(e) => {
            eprintln!("playbox pack: failed to read {}: {}", input, e);
            return 1;
        }
    };

    let sym = symbol.map(|s| c_ident(s)).unwrap_or_else(|| file_stem_ident(input));
    let note = format!(
        "source: {} ({} bytes)",
                       Path::new(input).file_name().and_then(|x| x.to_str()).unwrap_or(input),
                       data.len()
    );

    let body = if kind == "text" { emit_text(&sym, &data, &note) } else { emit_bin(&sym, &data, &note) };

    if let Err(e) = write_header("playbox_assets", output, &body) {
        eprintln!("playbox pack: failed to write {}: {}", output, e);
        return 1;
    }

    println!("wrote {} (symbol={} len={})", output, sym, data.len());
    0
}

/* ------------------------- demo/record/replay ------------------------- */

fn cmd_demo(name: &str, bin_dir: Option<&str>) -> i32 {
    let exe = match find_demo(bin_dir, name) {
        Some(p) => p,
        None => {
            eprintln!("playbox demo: could not find demo '{}' in bin dirs", name);
            return 1;
        }
    };
    run_demo(&exe, &[])
}

fn cmd_record(name: &str, out_file: &str, bin_dir: Option<&str>) -> i32 {
    let exe = match find_demo(bin_dir, name) {
        Some(p) => p,
        None => {
            eprintln!("playbox record: could not find demo '{}' in bin dirs", name);
            return 1;
        }
    };
    run_demo(&exe, &[("PLAYBOX_RECORD", out_file)])
}

fn cmd_replay(name: &str, in_file: &str, bin_dir: Option<&str>) -> i32 {
    let exe = match find_demo(bin_dir, name) {
        Some(p) => p,
        None => {
            eprintln!("playbox replay: could not find demo '{}' in bin dirs", name);
            return 1;
        }
    };
    run_demo(&exe, &[("PLAYBOX_REPLAY", in_file)])
}

fn main() {
    let mut args: Vec<String> = env::args().skip(1).collect();
    if args.is_empty() { usage(); }

    let cmd = args.remove(0);

    let code = match cmd.as_str() {
        "doctor" => cmd_doctor(),
        "info" => cmd_info(),
        "cat" => cmd_cat(),

        "pack-text" | "pack-bin" => {
            if args.is_empty() { usage(); }
            let input = args.remove(0);

            let mut output: Option<String> = None;
            let mut symbol: Option<String> = None;

            let mut i = 0;
            while i < args.len() {
                match args[i].as_str() {
                    "-o" | "--output" => {
                        if i + 1 >= args.len() { usage(); }
                        output = Some(args[i + 1].clone());
                        i += 2;
                    }
                    "--symbol" => {
                        if i + 1 >= args.len() { usage(); }
                        symbol = Some(args[i + 1].clone());
                        i += 2;
                    }
                    _ => usage(),
                }
            }

            let out = match output {
                Some(o) => o,
                None => { eprintln!("playbox {}: missing -o <output.h>", cmd); return; }
            };

            let kind = if cmd == "pack-text" { "text" } else { "bin" };
            cmd_pack(kind, &input, &out, symbol.as_deref())
        }

        "demo" => {
            if args.is_empty() { usage(); }
            let name = args.remove(0);
            let mut bin_dir: Option<String> = None;

            let mut i = 0;
            while i < args.len() {
                match args[i].as_str() {
                    "--bin-dir" => { if i+1>=args.len(){usage();} bin_dir=Some(args[i+1].clone()); i+=2; }
                    _ => usage(),
                }
            }
            cmd_demo(&name, bin_dir.as_deref())
        }

        "record" => {
            if args.is_empty() { usage(); }
            let name = args.remove(0);
            let mut out: Option<String> = None;
            let mut bin_dir: Option<String> = None;

            let mut i = 0;
            while i < args.len() {
                match args[i].as_str() {
                    "-o" => { if i+1>=args.len(){usage();} out=Some(args[i+1].clone()); i+=2; }
                    "--bin-dir" => { if i+1>=args.len(){usage();} bin_dir=Some(args[i+1].clone()); i+=2; }
                    _ => usage(),
                }
            }
            let out = out.unwrap_or_else(|| { eprintln!("playbox record: missing -o <file.pbr>"); std::process::exit(2) });
            cmd_record(&name, &out, bin_dir.as_deref())
        }

        "replay" => {
            if args.is_empty() { usage(); }
            let name = args.remove(0);
            let mut inp: Option<String> = None;
            let mut bin_dir: Option<String> = None;

            let mut i = 0;
            while i < args.len() {
                match args[i].as_str() {
                    "-i" => { if i+1>=args.len(){usage();} inp=Some(args[i+1].clone()); i+=2; }
                    "--bin-dir" => { if i+1>=args.len(){usage();} bin_dir=Some(args[i+1].clone()); i+=2; }
                    _ => usage(),
                }
            }
            let inp = inp.unwrap_or_else(|| { eprintln!("playbox replay: missing -i <file.pbr>"); std::process::exit(2) });
            cmd_replay(&name, &inp, bin_dir.as_deref())
        }

        _ => usage(),
    };

    std::process::exit(code);
}
